
apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  labels:
    app: java
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: farhanregistery/java-web-app:latest
        ports:
        - containerPort: 8080

